US-04, US-05 e página Home
mdsreq-fga-unb/2023.1-MoViagem pull request #36
Opened 2023-06-16 01:07 UTC by JoaoSchmitz

As US-04 e US-05 foram feitas completamente e a página Home foi criada.

2023-06-16 01:14 UTC, JoaoSchmitz commented
Lembrar de, após fazer o merge, mudar a src da imagem da Home, pois está atualmente usando uma url para um repositório próprio meu. Portanto, após unir com a main, mudar para a url da imagem presente no path: client\src\assets\HomeImage.png

2023-06-17 02:36 UTC, scikera approved these changes
Não foi encontrado nenhum erro

2023-06-17 16:07 UTC, Eduardo-RFarias requested changes
Eu criei alguns comentários pontuais de coisas que devem ser resolvidas antes do merge, o resto está certo.

2023-06-17 16:07 UTC, Eduardo-RFarias commented on client/src/pages/EditUserInfo/index.tsx
> +  console.log(auth?.userInfo?.name);
tem um console log aqui

2023-06-17 16:07 UTC, Eduardo-RFarias commented on client/src/components/Navbar/index.tsx
> +  window.location.href = "/user-info";
no react SPA é melhor redirecionar usando o hook [useNavigate](https://reactrouter.com/en/main/hooks/use-navigate). Usar o location reseta o estado de todos os contexts.

2023-06-17 16:07 UTC, Eduardo-RFarias commented on client/src/pages/Home/index.tsx
> +          <img alt="MóViagem logo" src="https://raw.githubusercontent.com/JoaoSchmitz/Teste/master/HomeImage.png?token=GHSAT0AAAAAACDMYOL35YDA6AYFL4PRFORCZELWVTA" ></img>
isso aqui pode dar problema, upa a imagem na pasta assets e inclui aqui. Esse link pode mudar a qualquer momento além de expor o seu token de autenticação pra todo mundo.

2023-06-17 16:07 UTC, Eduardo-RFarias commented on client/src/pages/Travels/index.tsx
>  import Navbar from "../../components/Navbar";
Essa página era só um placeholder, pode apagar ela.

2023-06-17 16:07 UTC, Eduardo-RFarias commented on server/.example.env
por favor, não apague esse arquivo.

2023-06-17 16:07 UTC, Eduardo-RFarias commented on server/src/auth/repositories/user.repository.ts
> +    console.log("nova senha: ", data)
tem um console log aqui.

2023-06-17 16:07 UTC, Eduardo-RFarias commented on server/src/auth/services/user.service.ts
> +    console.log(userAlreadyExist);
console log

2023-06-17 21:59 UTC, Eduardo-RFarias approved these changes
Tudo ok

2023-06-18 18:36 UTC, merged